import { google } from 'googleapis'
import { YoutubeTranscript } from 'youtube-transcript'

// YouTube Data API v3 設定
const youtube = google.youtube({
  version: 'v3'
})

export interface YouTubeVideoInfo {
  id: string
  title: string
  description: string
  duration: number
  thumbnailUrl: string
}

export interface TranscriptItem {
  start: number
  dur: number
  text: string
}

export interface CaptionTrack {
  id: string
  name: string
  language: string
  kind: string
  isAutoGenerated: boolean
}

export interface CaptionItem {
  start: number
  dur: number
  text: string
}

/**
 * YouTube動画IDから動画情報を取得
 */
export async function getVideoInfo(videoId: string): Promise<YouTubeVideoInfo> {
  try {
    const response = await youtube.videos.list({
      part: ['snippet', 'contentDetails'],
      id: [videoId],
      key: process.env.YOUTUBE_API_KEY
    })

    const video = response.data.items?.[0]
    if (!video) {
      throw new Error('Video not found')
    }

    const snippet = video.snippet!
    const contentDetails = video.contentDetails!
    
    // ISO 8601 duration を秒に変換
    const duration = parseDuration(contentDetails.duration!)
    
    return {
      id: videoId,
      title: snippet.title!,
      description: snippet.description || '',
      duration,
      thumbnailUrl: snippet.thumbnails?.maxres?.url || snippet.thumbnails?.high?.url || ''
    }
  } catch (error) {
    console.error('Error fetching video info:', error)
    throw new Error('Failed to fetch video information')
  }
}

/**
 * 動画の利用可能な字幕リストを取得
 */
export async function getCaptionsList(videoId: string): Promise<CaptionTrack[]> {
  try {
    console.log(`Fetching captions list for video: ${videoId}`)

    const response = await youtube.captions.list({
      part: ['snippet'],
      videoId: videoId,
      key: process.env.YOUTUBE_API_KEY
    })

    const captions = response.data.items || []
    console.log(`Raw captions response:`, JSON.stringify(captions, null, 2))

    const result = captions.map(caption => ({
      id: caption.id!,
      name: caption.snippet?.name || '',
      language: caption.snippet?.language || '',
      kind: caption.snippet?.trackKind || 'standard',
      isAutoGenerated: caption.snippet?.trackKind === 'ASR'
    }))

    console.log(`Processed captions:`, result)
    return result
  } catch (error) {
    console.error('Error fetching captions list:', error)
    throw new Error('字幕リストの取得に失敗しました')
  }
}

/**
 * 字幕をダウンロードして解析
 */
export async function downloadCaption(captionId: string, format: string = 'srt'): Promise<CaptionItem[]> {
  try {
    console.log(`Downloading caption: ${captionId} in format: ${format}`)

    const response = await youtube.captions.download({
      id: captionId,
      tfmt: format,
      key: process.env.YOUTUBE_API_KEY
    })

    const captionText = response.data as string
    console.log(`Downloaded caption text length: ${captionText.length}`)

    if (format === 'srt') {
      const result = parseSrtCaption(captionText)
      console.log(`Parsed ${result.length} SRT caption items`)
      return result
    } else if (format === 'ttml') {
      const result = parseTtmlCaption(captionText)
      console.log(`Parsed ${result.length} TTML caption items`)
      return result
    }

    throw new Error(`Unsupported format: ${format}`)
  } catch (error) {
    console.error('Error downloading caption:', error)
    throw new Error('字幕のダウンロードに失敗しました')
  }
}

/**
 * YouTube動画のトランスクリプトを取得（YouTube Data API v3使用）
 */
export const getVideoTranscript = async (videoId: string): Promise<TranscriptItem[]> => {
  try {
    console.log(`Getting transcript for video: ${videoId}`)

    // まずYouTube Data API v3で字幕を取得
    const captions = await getCaptionsList(videoId)
    console.log(`Found ${captions.length} caption tracks`)

    // 日本語または英語の字幕のみをフィルタリング
    const supportedCaptions = captions.filter(c => c.language === 'ja' || c.language === 'en')
    console.log(`Found ${supportedCaptions.length} supported caption tracks (ja/en)`)

    if (supportedCaptions.length > 0) {
      // 日本語字幕を優先、なければ英語
      const selectedCaption = supportedCaptions.find(c => c.language === 'ja') ||
                           supportedCaptions.find(c => c.language === 'en')!

      console.log(`Selected caption: ${selectedCaption.language} (${selectedCaption.name})`)

      const captionItems = await downloadCaption(selectedCaption.id, 'srt')
      console.log(`Downloaded ${captionItems.length} caption items`)

      return captionItems.map(item => ({
        start: item.start,
        dur: item.dur,
        text: item.text
      }))
    }

    // YouTube Data APIで字幕が取得できない場合、youtube-transcriptライブラリを試行
    try {
      const transcriptData = await YoutubeTranscript.fetchTranscript(videoId)

      if (transcriptData && transcriptData.length > 0) {
        return transcriptData.map((item) => ({
          start: Math.floor(item.offset / 1000),
          dur: Math.floor(item.duration / 1000),
          text: item.text
        }))
      }
    } catch (transcriptError) {
      console.warn('youtube-transcript also failed:', transcriptError)
    }

    // フォールバック: デモ用のトランスクリプトを生成
    return generateDemoTranscript()

  } catch (error) {
    console.error('Failed to get transcript:', error)
    throw new Error('トランスクリプトの取得に失敗しました')
  }
}

/**
 * デモ用のトランスクリプトを生成
 */
function generateDemoTranscript(): TranscriptItem[] {
  const demoTexts = [
    "Welcome to this video tutorial.",
    "Today we'll be learning about new technologies.",
    "Let's start with the basics and work our way up.",
    "This is an important concept to understand.",
    "Here's how you can implement this feature.",
    "Don't forget to test your implementation.",
    "That's all for today's tutorial.",
    "Thanks for watching and see you next time!"
  ]
  
  return demoTexts.map((text, index) => ({
    start: index * 30, // 30秒間隔
    dur: 25, // 25秒間
    text: text
  }))
}

/**
 * YouTube URLから動画IDを抽出
 */
export function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/v\/([a-zA-Z0-9_-]{11})/
  ]

  for (const pattern of patterns) {
    const match = url.match(pattern)
    if (match) {
      return match[1]
    }
  }

  return null
}

/**
 * SRT形式の字幕を解析
 */
function parseSrtCaption(srtText: string): CaptionItem[] {
  const items: CaptionItem[] = []
  const blocks = srtText.trim().split('\n\n')

  for (const block of blocks) {
    const lines = block.split('\n')
    if (lines.length < 3) continue

    const timeLine = lines[1]
    const textLines = lines.slice(2)

    const timeMatch = timeLine.match(/(\d{2}):(\d{2}):(\d{2}),(\d{3}) --> (\d{2}):(\d{2}):(\d{2}),(\d{3})/)
    if (!timeMatch) continue

    const startTime = parseTime(timeMatch[1], timeMatch[2], timeMatch[3], timeMatch[4])
    const endTime = parseTime(timeMatch[5], timeMatch[6], timeMatch[7], timeMatch[8])

    items.push({
      start: startTime,
      dur: endTime - startTime,
      text: textLines.join(' ').replace(/<[^>]*>/g, '') // HTMLタグを除去
    })
  }

  return items
}

/**
 * TTML形式の字幕を解析
 */
function parseTtmlCaption(ttmlText: string): CaptionItem[] {
  const items: CaptionItem[] = []

  // 簡単なTTML解析（実際のプロダクションではより堅牢なXMLパーサーを使用）
  const pRegex = /<p[^>]*begin="([^"]*)"[^>]*end="([^"]*)"[^>]*>(.*?)<\/p>/gs
  let match

  while ((match = pRegex.exec(ttmlText)) !== null) {
    const startTime = parseTimeCode(match[1])
    const endTime = parseTimeCode(match[2])
    const text = match[3].replace(/<[^>]*>/g, '') // HTMLタグを除去

    items.push({
      start: startTime,
      dur: endTime - startTime,
      text: text.trim()
    })
  }

  return items
}

/**
 * 時間文字列を秒に変換
 */
function parseTime(hours: string, minutes: string, seconds: string, milliseconds: string): number {
  return parseInt(hours) * 3600 + parseInt(minutes) * 60 + parseInt(seconds) + parseInt(milliseconds) / 1000
}

/**
 * TTMLの時間コードを秒に変換
 */
function parseTimeCode(timeCode: string): number {
  if (timeCode.includes(':')) {
    const parts = timeCode.split(':')
    if (parts.length === 3) {
      const [hours, minutes, seconds] = parts
      return parseInt(hours) * 3600 + parseInt(minutes) * 60 + parseFloat(seconds)
    }
  }
  return parseFloat(timeCode) || 0
}

/**
 * ISO 8601 duration を秒に変換
 */
function parseDuration(duration: string): number {
  const match = duration.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/)
  if (!match) return 0

  const hours = parseInt(match[1] || '0', 10)
  const minutes = parseInt(match[2] || '0', 10)
  const seconds = parseInt(match[3] || '0', 10)

  return hours * 3600 + minutes * 60 + seconds
}